/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateNetworkAccountRequest
 */
export interface CreateNetworkAccountRequest {
	/**
	 * The account handle to create (e.g., \'graphtracks.com\')
	 * @type {string}
	 * @memberof CreateNetworkAccountRequest
	 */
	account_handle: string;
	/**
	 * The network to create an account for. Only BlueSky is supported right now.
	 * @type {string}
	 * @memberof CreateNetworkAccountRequest
	 */
	network?: CreateNetworkAccountRequestNetworkEnum;
}

export const CreateNetworkAccountRequestNetworkEnum = {
	BlueSky: "BlueSky",
} as const;

export type CreateNetworkAccountRequestNetworkEnum =
	(typeof CreateNetworkAccountRequestNetworkEnum)[keyof typeof CreateNetworkAccountRequestNetworkEnum];
