/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeleteNetworkAccount201Response
 */
export interface DeleteNetworkAccount201Response {
	/**
	 *
	 * @type {string}
	 * @memberof DeleteNetworkAccount201Response
	 */
	message?: string;
}
