/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Interaction
 */
export interface Interaction {
    /**
     * The timestamp for this interaction. UTC timezone.
     * @type {string}
     * @memberof Interaction
     */
    'time': string;
    /**
     * The user id who performed the interaction
     * @type {string}
     * @memberof Interaction
     */
    'id': string;
    /**
     * The user profile information
     * @type {object}
     * @memberof Interaction
     */
    'profile'?: object;
}

