/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NetworkStatsResponse
 */
export interface NetworkStatsResponse {
    /**
     * Total number of users
     * @type {number}
     * @memberof NetworkStatsResponse
     */
    'total_users': number;
    /**
     * Total number of posts
     * @type {number}
     * @memberof NetworkStatsResponse
     */
    'total_posts': number;
    /**
     * Total number of follow actions
     * @type {number}
     * @memberof NetworkStatsResponse
     */
    'total_follows': number;
    /**
     * Total number of likes
     * @type {number}
     * @memberof NetworkStatsResponse
     */
    'total_likes': number;
}

