/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostData
 */
export interface PostData {
	/**
	 * The number of likes on the post
	 * @type {number}
	 * @memberof PostData
	 */
	likes?: number;
	/**
	 * The number of reposts
	 * @type {number}
	 * @memberof PostData
	 */
	reposts?: number;
	/**
	 * The number of replies
	 * @type {number}
	 * @memberof PostData
	 */
	replies?: number;
	/**
	 * The total engagement metric
	 * @type {number}
	 * @memberof PostData
	 */
	engagement?: number;
	/**
	 * Additional post details
	 * @type {object}
	 * @memberof PostData
	 */
	details?: object;
	/**
	 * The timestamp for when the post was indexed
	 * @type {string}
	 * @memberof PostData
	 */
	indexedAt?: string;
}
