/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserDetails } from './user-details';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * The user id
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * The external id
     * @type {string}
     * @memberof User
     */
    'external_id': string;
    /**
     * The timestamp for when the user was created
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * The timestamp for when the user was last updated
     * @type {string}
     * @memberof User
     */
    'updated_at'?: string;
    /**
     * 
     * @type {UserDetails}
     * @memberof User
     */
    'details'?: UserDetails;
}

