/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The user email
 * @export
 * @interface UserDetailsEmail
 */
export interface UserDetailsEmail {
    /**
     * The user email address
     * @type {string}
     * @memberof UserDetailsEmail
     */
    'address'?: string;
    /**
     * Whether the user email is verified
     * @type {boolean}
     * @memberof UserDetailsEmail
     */
    'is_verified'?: boolean;
    /**
     * Whether the user email is the primary email
     * @type {boolean}
     * @memberof UserDetailsEmail
     */
    'is_primary'?: boolean;
}

