/* tslint:disable */
/* eslint-disable */
/**
 * GraphTracks Analytics API
 * Bluesky Analytics API for GraphTracks
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserDetailsEmail } from './user-details-email';

/**
 * The user details
 * @export
 * @interface UserDetails
 */
export interface UserDetails {
    /**
     * 
     * @type {UserDetailsEmail}
     * @memberof UserDetails
     */
    'email'?: UserDetailsEmail;
}

